"""
V1-G: Comparison analyst checkpoints.

ComparisonCheckpoints are generated by policy-driven rules during schedule
comparison runs. A PENDING blocking checkpoint indicates that unresolved
divergences prevent analyst reliance on the comparison result.

Follows the same governance model as SimCheckpoint (V1-E ADR-015) and
DSTCheckpoint (V1-D ADR-014): no silent suppression, sequential IDs,
analyst-visible lifecycle.

Source: ADR-016.

Ported from the LI MIP 3.9 tool (mip39.comparison_validation.checkpoints) per ADR-0007 — port-and-validate.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from .divergences import DivergenceCategory


class ComparisonCheckpointStatus(Enum):
    """Resolution status of a comparison checkpoint."""
    PENDING = "pending"
    ACKNOWLEDGED = "acknowledged"
    WAIVED = "waived"
    RESOLVED = "resolved"


@dataclass
class ComparisonCheckpoint:
    """
    A single analyst checkpoint generated during a comparison run.

    Fields:
        checkpoint_id:      Sequential identifier (e.g. "CCP-001").
        reason:             Human-readable explanation of why this checkpoint exists.
        divergence_ids:     DIV-NNN IDs of divergences that triggered this checkpoint.
        act_ids:            Activity IDs involved, if applicable.
        div_category:       DivergenceCategory that triggered this checkpoint.
        is_blocking:        If True, comparison result cannot be relied upon until
                            this checkpoint is ACKNOWLEDGED or WAIVED.
        status:             Current resolution status.
        resolution_note:    Optional analyst note recorded at resolution.
    """

    checkpoint_id: str
    reason: str
    divergence_ids: list[str] = field(default_factory=list)
    act_ids: list[str] = field(default_factory=list)
    div_category: DivergenceCategory = DivergenceCategory.UNKNOWN_DIFFERENCE
    is_blocking: bool = True
    status: ComparisonCheckpointStatus = ComparisonCheckpointStatus.PENDING
    resolution_note: str = ""

    def acknowledge(self, note: str = "") -> None:
        self.status = ComparisonCheckpointStatus.ACKNOWLEDGED
        self.resolution_note = note

    def waive(self, note: str) -> None:
        self.status = ComparisonCheckpointStatus.WAIVED
        self.resolution_note = note

    def resolve(self, note: str = "") -> None:
        self.status = ComparisonCheckpointStatus.RESOLVED
        self.resolution_note = note

    def is_unresolved(self) -> bool:
        return self.status == ComparisonCheckpointStatus.PENDING

    def to_dict(self) -> dict[str, Any]:
        return {
            "checkpoint_id": self.checkpoint_id,
            "reason": self.reason,
            "divergence_ids": list(self.divergence_ids),
            "act_ids": list(self.act_ids),
            "div_category": self.div_category.value,
            "is_blocking": self.is_blocking,
            "status": self.status.value,
            "resolution_note": self.resolution_note,
        }


@dataclass
class ComparisonCheckpointRegistry:
    """
    Ordered collection of ComparisonCheckpoints for a comparison run.

    Fields:
        _checkpoints: Insertion-ordered list.
        _counter:     Sequential ID counter.
    """

    _checkpoints: list[ComparisonCheckpoint] = field(default_factory=list)
    _counter: int = field(default=0)

    def next_id(self) -> str:
        self._counter += 1
        return f"CCP-{self._counter:03d}"

    def add(self, cp: ComparisonCheckpoint) -> None:
        self._checkpoints.append(cp)

    def all(self) -> list[ComparisonCheckpoint]:
        return list(self._checkpoints)

    def unresolved_blocking(self) -> list[ComparisonCheckpoint]:
        return [cp for cp in self._checkpoints if cp.is_blocking and cp.is_unresolved()]

    def is_comparison_blocked(self) -> bool:
        return any(cp.is_blocking and cp.is_unresolved() for cp in self._checkpoints)

    def __len__(self) -> int:
        return len(self._checkpoints)

    def to_dict_list(self) -> list[dict[str, Any]]:
        return [cp.to_dict() for cp in self._checkpoints]
